### PR TITLE
Use ILevelEditor instead of LevelEditor

### PR DESCRIPTION
**Pull request by seannowotny**
I haven't tested this but I hope it is better 😅

### CODE REVIEW

**Comment by Hertzole** [comment]
Looks good and makes sense to use that instead.

**Comment by seannowotny** [comment]
Damn

**Comment by seannowotny** [comment]
Now I'm even less sure this works https://answers.unity.com/questions/863509/how-can-i-find-all-objects-that-have-a-script-that.html

**Comment by Hertzole** [comment]
Oh yeah, you're right. You can't find interfaces like that, unfortunately.

**Pull request merged**
